feat(workflow) : add dynamic environment

diff --git a/.github/workflows/app-deploy.yaml b/.github/workflows/app-deploy.yaml
--- a/.github/workflows/app-deploy.yaml
+++ b/.github/workflows/app-deploy.yaml
@@ -2,7 +2,7 @@ name: App Deploy
 
 on:
   push:
-    branches: [main]
+    branches: [main, develop]
     paths:
       - 'src/**'
       - 'pom.xml'
@@ -13,7 +13,36 @@ permissions:
   contents: read
 
 jobs:
+
+  set_environment:
+    runs-on: ubuntu-latest
+    outputs:
+      environment: ${{ steps.branch_map.outputs.environment }}
+
+    steps:
+      - id: branch_map
+        run: |
+          BRANCH_NAME="${{ github.ref_name }}"
+          ENVIRONMENT=""
+
+          case "$BRANCH_NAME" in
+            "develop")
+              ENVIRONMENT="dev"
+              ;;
+            "main")
+              ENVIRONMENT="prod"
+              ;;
+            *)
+              echo "Branch $BRANCH_NAME não mapeada. Abortando."
+              exit 1
+              ;;
+          esac
+
+          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
+          echo "Ambiente mapeado: $ENVIRONMENT"
+
   build:
+    needs: set_environment
     uses: ./.github/workflows/docker.yaml
     with:
       image_name: soatproject/hackaton-soat-manager
@@ -23,9 +52,9 @@ jobs:
       DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
 
   deploy:
-    needs: build
+    needs: [set_environment, build]
     uses: ./.github/workflows/terraform.yaml
     with:
-      environment: prod
+      environment: ${{ needs.set_environment.outputs.environment }}
       image_tag: ${{ github.sha }}
     secrets: inherit
